name: Generate TWRP Device Tree

on:
  workflow_dispatch:
    inputs:
      LIBRARY_NAME:
        description: 'Library name for the device tree'
        required: true
        default: 'Twrp_Device_Generator'
      IMG_URL:
        description: 'URL to recovery/boot image'
        required: true
        default: 'https://media-nxzw-fy-person01.nx5oss.ctyunxs.cn/PERSONCLOUD/5c2a808a-b5cf-4dc8-97cd-03d749d80ba5.img?x-amz-CLIENTTYPEIN=UNKNOWN&AWSAccessKeyId=g6jU1T3TkAbPKf5ouH5d&x-amz-userLevel=7&x-amz-limitrate=51200&x-amz-UID=826925900&x-amz-APPID=828221&response-content-disposition=attachment%3Bfilename%3D%22recovery.img%22%3Bfilename*%3DUTF-8%27%27recovery.img&x-amz-CLIENTNETWORK=UNKNOWN&x-amz-CLOUDTYPEIN=PERSON&Signature=IMVgRriSM2WRuiM7IXHGTbaxXAo%3D&x-amz-SHID=12393116606368&Expires=1749993331&x-amz-FSIZE=104857600&x-amz-UFID=925131199018089495'

jobs:
  generate-device-tree:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3 \
          python3-pip \
          cpio \
          wget \
          zip \
          unzip
        
    - name: Install TWRP generator
      run: |
        pip3 install --upgrade twrpdtgen
        
    - name: Download recovery image
      run: |
        wget -O recovery.img "${{ github.event.inputs.IMG_URL }}"
        file recovery.img || true  # Display file info for debugging
      
    - name: Generate device tree
      run: |
        mkdir -p device_tree_output
        python3 -m twrpdtgen \
          -o device_tree_output \
          recovery.img
        
    - name: Compress device tree
      run: |
        cd device_tree_output
        zip -r ../DeviceTree_${{ github.run_number }}.zip .
        cd ..
        
    - name: Create release with device tree
      uses: softprops/action-gh-release@v1
      with:
        files: DeviceTree_${{ github.run_number }}.zip
        name: TWRP_Device_Tree_${{ github.run_number }}
        tag_name: dt-${{ github.run_number }}
        body: |
          Automatically generated TWRP device tree
          Build run: ${{ github.run_number }}
          Source image: ${{ github.event.inputs.IMG_URL }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
